apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p1w3e1wwh-dotnet-basic
  janus-idp.io/tekton: p1w3e1wwh-dotnet-basic
  backstage.io/kubernetes-id: p1w3e1wwh-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p1w3e1wwh-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
